### ISSUE TITLE
Need Wiring Diagram

### ISSUE THREAD

**Issue by CornDogLover999** [QiTech-Industries/winder-parts#3]
Is there a wiring diagram for this?  I need one as I can't determine if one of my components is fatly or not.  I am also making a step by step guide on how to assembly this but need to get it working first before I upload.  Cannot get any steppers to work, am getting no movement.

**Comment by DreiDe** [comment]
@CornDogLover999 We used this spreadsheet for wiring: https://github.com/QiTech-Industries/Winder/blob/main/images/IMG_1544.jpeg

**Comment by CornDogLover999** [comment]
Thank You!
